version: "3.9"
services:
  db:
    build:
      # https://docs.docker.com/compose/compose-file/compose-file-v3/#dockerfile
      context: .
      # dockerfile: Dockerfile
      # https://docs.docker.com/compose/compose-file/compose-file-v3/#target
      target: database
    image: sql-sandbox-postgres-db
    container_name: sql-sandbox-postgres-db
    ports:
      # https://docs.docker.com/compose/compose-file/compose-file-v3/#ports
      - "5432:5432"
    volumes:
      # https://hub.docker.com/_/postgres
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sql_sandbox_postgres
    restart: always
volumes:
  pgdata:
